import { randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = path.resolve(
  process.env.PHD_ATLAS_PROJECT_ROOT || path.resolve(scriptDir, '..')
)
const STORAGE_ROOT = path.join(PROJECT_ROOT, 'storage')
const SECRETS_PATH = path.join(STORAGE_ROOT, 'bootstrap-secrets.json')

/**
 * Generate a cryptographically random base64url secret.
 * @param {number} [bytes=48]
 */
function generateSecret(bytes = 48) {
  return randomBytes(bytes).toString('base64url')
}

/**
 * Attempt to read persisted secrets from storage.
 * @returns {{ jwtSecret: string, encryptionKey: string } | null}
 */
function readPersistedSecrets() {
  try {
    if (!existsSync(SECRETS_PATH)) return null
    const raw = readFileSync(SECRETS_PATH, 'utf8')
    const parsed = JSON.parse(raw)
    if (parsed.jwtSecret && parsed.encryptionKey) return parsed
    return null
  } catch {
    return null
  }
}

/**
 * Persist secrets to storage with restrictive permissions.
 */
function persistSecrets(jwtSecret, encryptionKey) {
  mkdirSync(STORAGE_ROOT, { recursive: true })
  writeFileSync(
    SECRETS_PATH,
    JSON.stringify(
      {
        jwtSecret,
        encryptionKey,
        createdAt: new Date().toISOString(),
      },
      null,
      2
    ),
    { encoding: 'utf8', mode: 0o600 }
  )
}

// Cached resolved values
let _jwtSecret = null
let _encryptionKey = null

/**
 * Resolve JWT_SECRET and SETTINGS_ENCRYPTION_KEY:
 * 1. Use explicit env vars if both are valid (backward compatible).
 * 2. Read persisted bootstrap-secrets.json from storage/.
 * 3. Auto-generate in production; use dev defaults otherwise.
 */
export function resolveBootstrapSecrets() {
  if (_jwtSecret && _encryptionKey)
    return { jwtSecret: _jwtSecret, encryptionKey: _encryptionKey }

  const envJwt = process.env.JWT_SECRET
  const envEncKey = process.env.SETTINGS_ENCRYPTION_KEY
  const bothFromEnv =
    envJwt &&
    envEncKey &&
    envJwt.length >= 32 &&
    envEncKey.length >= 16 &&
    envJwt !== 'phd-atlas-local-dev-secret'

  const persisted = readPersistedSecrets()

  if (bothFromEnv) {
    _jwtSecret = envJwt
    _encryptionKey = envEncKey
    // Sync to file so the admin UI and restarts see the canonical copy
    if (
      !persisted ||
      persisted.jwtSecret !== envJwt ||
      persisted.encryptionKey !== envEncKey
    ) {
      persistSecrets(envJwt, envEncKey)
    }
  } else if (persisted) {
    _jwtSecret = persisted.jwtSecret
    _encryptionKey = persisted.encryptionKey
  } else if (process.env.NODE_ENV === 'production') {
    // Auto-generate in production — the first boot creates the keys
    _jwtSecret = envJwt && envJwt.length >= 32 ? envJwt : generateSecret(48)
    _encryptionKey =
      envEncKey && envEncKey.length >= 16 ? envEncKey : generateSecret(48)
    persistSecrets(_jwtSecret, _encryptionKey)
    console.log(
      '🔐 Auto-generated security keys — persisted to storage/bootstrap-secrets.json'
    )
  } else {
    // Dev: use defaults so local dev doesn't need .env
    _jwtSecret = envJwt || 'phd-atlas-local-dev-secret'
    _encryptionKey = envEncKey || 'phd-atlas-dev-encryption-key'
  }

  // Production safety net: if we still have the dev default, regenerate
  if (
    process.env.NODE_ENV === 'production' &&
    _jwtSecret === 'phd-atlas-local-dev-secret'
  ) {
    _jwtSecret = generateSecret(48)
    _encryptionKey = generateSecret(48)
    persistSecrets(_jwtSecret, _encryptionKey)
  }

  return { jwtSecret: _jwtSecret, encryptionKey: _encryptionKey }
}

/**
 * Regenerate both secrets and persist. This invalidates all existing sessions
 * and any data encrypted with the old key — the caller must manage the migration.
 */
export function regenerateBootstrapSecrets() {
  _jwtSecret = generateSecret(48)
  _encryptionKey = generateSecret(48)
  persistSecrets(_jwtSecret, _encryptionKey)
  return { jwtSecret: _jwtSecret, encryptionKey: _encryptionKey }
}

/**
 * Return cached secrets (call resolveBootstrapSecrets() first).
 */
export function getBootstrapSecrets() {
  if (!_jwtSecret || !_encryptionKey) {
    return resolveBootstrapSecrets()
  }
  return { jwtSecret: _jwtSecret, encryptionKey: _encryptionKey }
}

/**
 * Check whether secrets were auto-generated (not supplied via env).
 */
export function isSecretsAutoGenerated() {
  const envJwt = process.env.JWT_SECRET
  const envEncKey = process.env.SETTINGS_ENCRYPTION_KEY
  const bothFromEnv =
    envJwt &&
    envEncKey &&
    envJwt.length >= 32 &&
    envEncKey.length >= 16 &&
    envJwt !== 'phd-atlas-local-dev-secret'
  return !bothFromEnv
}

/**
 * Derive URL configuration from a single DOMAIN env var.
 * DOMAIN can be a full URL ("https://phd.example.com") or just a hostname.
 */
export function deriveConfigFromDomain() {
  const domain = process.env.DOMAIN
  if (!domain) return null

  let baseUrl = domain
  if (!/^https?:\/\//i.test(baseUrl)) {
    baseUrl = `https://${baseUrl}`
  }
  baseUrl = baseUrl.replace(/\/+$/, '')

  try {
    const url = new URL(baseUrl)
    const hostname = url.hostname
    const port = url.port ? `:${url.port}` : ''

    return {
      BASE_URL: baseUrl,
      CORS_ORIGIN: baseUrl,
      ALLOWED_HOSTS: hostname + port,
    }
  } catch {
    console.error('Invalid DOMAIN value:', domain)
    return null
  }
}
