const US_PATH_HINTS = Object.freeze({
  faculty: Object.freeze([
    'faculty',
    'people',
    'directory',
    'profile',
    'profiles',
    'expert',
    'experts',
    'researcher',
    'researchers',
    'professor',
    'professors',
    'advisor',
    'adviser',
    'mentor',
    'mentors',
  ]),
  lab: Object.freeze([
    'research',
    'lab',
    'labs',
    'laboratory',
    'laboratories',
    'group',
    'groups',
    'center',
    'centers',
    'centre',
    'centres',
    'institute',
    'institutes',
    'initiative',
    'initiatives',
    'facility',
    'facilities',
  ]),
  department: Object.freeze([
    'department',
    'departments',
    'school',
    'schools',
    'college',
    'colleges',
    'academic-unit',
    'academics',
    'discipline',
    'disciplines',
    'division',
    'divisions',
  ]),
  program: Object.freeze([
    'phd',
    'ph-d',
    'doctoral',
    'doctorate',
    'graduate',
    'postgraduate',
    'program',
    'programs',
    'degree',
    'degrees',
    'admission',
    'admissions',
    'apply',
    'application',
  ]),
})

export const SCHOOL_ADAPTERS_BATCH_02 = [
  {
    school: 'Columbia University',
    region: 'US',
    allowedHosts: ['www.tc.columbia.edu', 'www.cs.columbia.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.tc.columbia.edu/academics/department-listing/' },
      { kind: 'faculty', url: 'https://www.cs.columbia.edu/people/faculty/' },
      { kind: 'research', url: 'https://www.cs.columbia.edu/labs/' },
      { kind: 'doctoral', url: 'https://www.cs.columbia.edu/education/phd/requirements/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'New York University',
    region: 'US',
    allowedHosts: ['engineering.nyu.edu'],
    seeds: [
      { kind: 'departments', url: 'https://engineering.nyu.edu/academics/departments' },
      { kind: 'faculty', url: 'https://engineering.nyu.edu/staff-directory' },
      { kind: 'research', url: 'https://engineering.nyu.edu/research/centers' },
      { kind: 'doctoral', url: 'https://engineering.nyu.edu/academics/graduate/phd-hub/guidelines-policies-and-requirements' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Pennsylvania',
    region: 'US',
    allowedHosts: ['www.upenn.edu', 'directory.engineering.upenn.edu', 'research.upenn.edu', 'catalog.upenn.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.upenn.edu/academics/schools' },
      { kind: 'faculty', url: 'https://directory.engineering.upenn.edu/' },
      { kind: 'research', url: 'https://research.upenn.edu/research-at-penn/centers-institutes/' },
      { kind: 'doctoral', url: 'https://catalog.upenn.edu/graduate/programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Yale University',
    region: 'US',
    allowedHosts: ['www.yale.edu', 'medicine.yale.edu', 'research.yale.edu', 'gsas.yale.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.yale.edu/academics/departments-programs' },
      { kind: 'faculty', url: 'https://medicine.yale.edu/dfri/' },
      { kind: 'research', url: 'https://research.yale.edu/centers-institutes' },
      { kind: 'doctoral', url: 'https://gsas.yale.edu/programs-of-study' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Duke University',
    region: 'US',
    allowedHosts: ['trinity.duke.edu', 'gradschool.duke.edu', 'medicine.duke.edu'],
    seeds: [
      { kind: 'departments', url: 'https://trinity.duke.edu/departments' },
      { kind: 'faculty', url: 'https://gradschool.duke.edu/academics/graduate-faculty/' },
      { kind: 'research', url: 'https://medicine.duke.edu/research/duke-institutes-and-centers' },
      { kind: 'doctoral', url: 'https://gradschool.duke.edu/academics/programs-and-degrees/phd-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Northwestern University',
    region: 'US',
    allowedHosts: ['www.mccormick.northwestern.edu', 'www.northwestern.edu', 'www.tgs.northwestern.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.mccormick.northwestern.edu/' },
      { kind: 'faculty', url: 'https://www.mccormick.northwestern.edu/research-faculty/directory/' },
      { kind: 'research', url: 'https://www.northwestern.edu/research-nu/research-institutes-centers.html' },
      { kind: 'doctoral', url: 'https://www.tgs.northwestern.edu/admission/academic-programs/explore-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Johns Hopkins University',
    region: 'US',
    allowedHosts: ['e-catalogue.jhu.edu', 'www.cs.jhu.edu'],
    seeds: [
      { kind: 'departments', url: 'https://e-catalogue.jhu.edu/engineering/full-time-residential-programs/' },
      { kind: 'faculty', url: 'https://www.cs.jhu.edu/faculty/' },
      { kind: 'research', url: 'https://www.cs.jhu.edu/research/' },
      { kind: 'doctoral', url: 'https://www.cs.jhu.edu/academic-programs/graduate-studies/phd-program/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Maryland, College Park',
    region: 'US',
    allowedHosts: ['umd.edu', 'faculty.eng.umd.edu', 'research.umd.edu', 'gradschool.umd.edu'],
    seeds: [
      { kind: 'departments', url: 'https://umd.edu/academic-departments-and-programs' },
      { kind: 'faculty', url: 'https://faculty.eng.umd.edu/' },
      { kind: 'research', url: 'https://research.umd.edu/about/division-offices-units' },
      { kind: 'doctoral', url: 'https://gradschool.umd.edu/admissions/all-graduate-programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Purdue University',
    region: 'US',
    allowedHosts: ['extension.purdue.edu', 'www.stat.purdue.edu', 'www.cs.purdue.edu', 'ag.purdue.edu'],
    seeds: [
      { kind: 'departments', url: 'https://extension.purdue.edu/anr/departments.html' },
      { kind: 'faculty', url: 'https://www.stat.purdue.edu/people/faculty/' },
      { kind: 'research', url: 'https://www.cs.purdue.edu/research/centers.html' },
      { kind: 'doctoral', url: 'https://ag.purdue.edu/department/arge/graduate-programs/graduate-programs-of-study.html' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Wisconsin-Madison',
    region: 'US',
    allowedHosts: ['www.wisc.edu', 'directory.engr.wisc.edu', 'research.wisc.edu', 'info.grad.wisc.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.wisc.edu/academics/departments-and-programs/' },
      { kind: 'faculty', url: 'https://directory.engr.wisc.edu/all/faculty/a/' },
      { kind: 'research', url: 'https://research.wisc.edu/centers-cores/' },
      { kind: 'doctoral', url: 'https://info.grad.wisc.edu/our-academic-programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Massachusetts Amherst',
    region: 'US',
    allowedHosts: ['www.isenberg.umass.edu', 'www.cics.umass.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.isenberg.umass.edu/programs/departments' },
      { kind: 'faculty', url: 'https://www.cics.umass.edu/about/directory/faculty' },
      { kind: 'research', url: 'https://www.cics.umass.edu/research' },
      { kind: 'doctoral', url: 'https://www.cics.umass.edu/academics/phd-computer-science' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Southern California',
    region: 'US',
    allowedHosts: ['dornsife.usc.edu', 'uscdirectory.usc.edu', 'research.usc.edu'],
    seeds: [
      { kind: 'departments', url: 'https://dornsife.usc.edu/departments/' },
      { kind: 'faculty', url: 'https://uscdirectory.usc.edu/web/directory/faculty-staff/' },
      { kind: 'research', url: 'https://research.usc.edu/research-and-scholarship/centers/' },
      { kind: 'doctoral', url: 'https://dornsife.usc.edu/doctoral-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of California, Davis',
    region: 'US',
    allowedHosts: ['www.ucdavis.edu', 'research.ucdavis.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.ucdavis.edu/academics/colleges-and-schools/academic-departments' },
      { kind: 'faculty', url: 'https://www.ucdavis.edu/academics/our-faculty' },
      { kind: 'research', url: 'https://research.ucdavis.edu/research-programs/' },
      { kind: 'doctoral', url: 'https://www.ucdavis.edu/academics/graduate' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of California, Irvine',
    region: 'US',
    allowedHosts: ['catalogue.uci.edu', 'engineering.uci.edu', 'ics.uci.edu'],
    seeds: [
      { kind: 'departments', url: 'https://catalogue.uci.edu/schoolsandprograms/' },
      { kind: 'faculty', url: 'https://engineering.uci.edu/directory/faculty' },
      { kind: 'research', url: 'https://ics.uci.edu/computing-research/' },
      { kind: 'doctoral', url: 'https://ics.uci.edu/academics/graduate-programs/graduate-research-phd-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of California, Santa Barbara',
    region: 'US',
    allowedHosts: ['www.ucsb.edu', 'engineering.ucsb.edu', 'www.graddiv.ucsb.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.ucsb.edu/academics/academic-departments-and-programs' },
      { kind: 'faculty', url: 'https://engineering.ucsb.edu/people/faculty' },
      { kind: 'research', url: 'https://engineering.ucsb.edu/research/research-centers' },
      { kind: 'doctoral', url: 'https://www.graddiv.ucsb.edu/graduate-programs/departments' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
]
