const US_PATH_HINTS = Object.freeze({
  faculty: Object.freeze([
    'faculty',
    'people',
    'directory',
    'profile',
    'profiles',
    'expert',
    'experts',
    'researcher',
    'professor',
    'advisor',
  ]),
  lab: Object.freeze([
    'research',
    'lab',
    'labs',
    'laboratory',
    'laboratories',
    'group',
    'groups',
    'center',
    'centers',
    'centre',
    'centres',
    'institute',
    'institutes',
    'facility',
    'facilities',
  ]),
  department: Object.freeze([
    'department',
    'departments',
    'school',
    'schools',
    'college',
    'colleges',
    'academic-unit',
    'academics',
    'discipline',
    'disciplines',
  ]),
  program: Object.freeze([
    'phd',
    'ph-d',
    'doctoral',
    'doctorate',
    'graduate',
    'postgraduate',
    'program',
    'programs',
    'degree',
    'degrees',
    'admission',
    'admissions',
  ]),
})

export const SCHOOL_ADAPTERS_BATCH_01 = [
  {
    school: 'Massachusetts Institute of Technology',
    region: 'US',
    allowedHosts: ['www.mit.edu', 'oge.mit.edu', 'www.eecs.mit.edu', 'www.csail.mit.edu', 'cee.mit.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.mit.edu/education/schools-and-departments/' },
      { kind: 'faculty', url: 'https://www.eecs.mit.edu/role/faculty/' },
      { kind: 'research', url: 'https://www.csail.mit.edu/research' },
      { kind: 'doctoral', url: 'https://www.eecs.mit.edu/academics/graduate-programs/' },
      { kind: 'doctoral', url: 'https://www.eecs.mit.edu/academics/graduate-programs/admission-process/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Stanford University',
    region: 'US',
    allowedHosts: ['engineering.stanford.edu', 'www.stanford.edu', 'gradadmissions.stanford.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.stanford.edu/academics/schools' },
      { kind: 'faculty', url: 'https://engineering.stanford.edu/faculty-research/faculty' },
      { kind: 'research', url: 'https://www.stanford.edu/research' },
      { kind: 'doctoral', url: 'https://gradadmissions.stanford.edu/explore-programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Carnegie Mellon University',
    region: 'US',
    allowedHosts: ['www.cs.cmu.edu', 'www.cmu.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.cmu.edu/academics' },
      { kind: 'faculty', url: 'https://www.cs.cmu.edu/directory/faculty' },
      { kind: 'research', url: 'https://www.cmu.edu/research-and-creativity' },
      { kind: 'doctoral', url: 'https://www.cs.cmu.edu/education/phd/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of California, Berkeley',
    region: 'US',
    allowedHosts: ['eecs.berkeley.edu', 'www.berkeley.edu', 'grad.berkeley.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.berkeley.edu/academics/schools-colleges/' },
      { kind: 'faculty', url: 'https://eecs.berkeley.edu/people/faculty/' },
      { kind: 'research', url: 'https://www.berkeley.edu/research/' },
      { kind: 'doctoral', url: 'https://grad.berkeley.edu/admissions/our-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Cornell University',
    region: 'US',
    allowedHosts: [
      'www.cs.cornell.edu',
      'www.cornell.edu',
      'research-and-innovation.cornell.edu',
      'gradschool.cornell.edu',
    ],
    seeds: [
      { kind: 'departments', url: 'https://www.cornell.edu/academics/colleges.cfm' },
      { kind: 'faculty', url: 'https://www.cs.cornell.edu/directory' },
      { kind: 'research', url: 'https://research-and-innovation.cornell.edu/centers/' },
      { kind: 'doctoral', url: 'https://gradschool.cornell.edu/academic-progress/degrees-fields/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Illinois Urbana-Champaign',
    region: 'US',
    allowedHosts: ['directory.illinois.edu', 'research.illinois.edu', 'grad.illinois.edu'],
    seeds: [
      { kind: 'departments', url: 'https://directory.illinois.edu/departmentsUnits' },
      { kind: 'faculty', url: 'https://directory.illinois.edu/facultyListing' },
      {
        kind: 'research',
        url: 'https://research.illinois.edu/about/research-centers-institutes-and-programs',
      },
      { kind: 'doctoral', url: 'https://grad.illinois.edu/admissions/programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Georgia Institute of Technology',
    region: 'US',
    allowedHosts: ['www.cc.gatech.edu', 'catalog.gatech.edu', 'research.gatech.edu'],
    seeds: [
      { kind: 'departments', url: 'https://catalog.gatech.edu/academics/colleges-and-schools/' },
      { kind: 'faculty', url: 'https://www.cc.gatech.edu/people/faculty' },
      { kind: 'research', url: 'https://research.gatech.edu/interdisciplinary-research-institutes' },
      { kind: 'doctoral', url: 'https://catalog.gatech.edu/academics/graduate/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Washington',
    region: 'US',
    allowedHosts: ['www.cs.washington.edu', 'www.washington.edu', 'grad.uw.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.washington.edu/about/academics/' },
      { kind: 'faculty', url: 'https://www.cs.washington.edu/people/faculty-members/' },
      { kind: 'research', url: 'https://www.washington.edu/research/' },
      { kind: 'doctoral', url: 'https://grad.uw.edu/programs/find-a-graduate-program/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Princeton University',
    region: 'US',
    allowedHosts: ['www.cs.princeton.edu', 'www.princeton.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.princeton.edu/academics/areas-of-study' },
      { kind: 'faculty', url: 'https://www.cs.princeton.edu/people/faculty' },
      { kind: 'research', url: 'https://www.princeton.edu/research' },
      { kind: 'doctoral', url: 'https://www.princeton.edu/academics/studying-princeton' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Harvard University',
    region: 'US',
    allowedHosts: ['seas.harvard.edu', 'www.harvard.edu', 'oira.harvard.edu', 'gsas.harvard.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.harvard.edu/academics/schools/' },
      { kind: 'faculty', url: 'https://seas.harvard.edu/faculty' },
      { kind: 'research', url: 'https://oira.harvard.edu/factbook/fact-book-initiatives/' },
      {
        kind: 'doctoral',
        url: 'https://gsas.harvard.edu/programs?f%5B0%5D=degrees_offered%3A157&f%5B1%5D=degrees_offered%3A158&f%5B2%5D=degrees_offered%3A352&field_degrees_offered=PhD&field_program_type=All',
      },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'California Institute of Technology',
    region: 'US',
    allowedHosts: ['www.caltech.edu', 'gradoffice.caltech.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.caltech.edu/academics' },
      { kind: 'faculty', url: 'https://www.caltech.edu/research/faculty-listing' },
      { kind: 'research', url: 'https://www.caltech.edu/research' },
      { kind: 'doctoral', url: 'https://gradoffice.caltech.edu/academics/degrees' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of California, Los Angeles',
    region: 'US',
    allowedHosts: [
      'samueli.ucla.edu',
      'registrar.ucla.edu',
      'catalog.registrar.ucla.edu',
      'grad.ucla.edu',
    ],
    seeds: [
      {
        kind: 'departments',
        url: 'https://registrar.ucla.edu/academics/departments-programs-and-freestanding-minors',
      },
      { kind: 'faculty', url: 'https://samueli.ucla.edu/faculty-expertise-directory/' },
      { kind: 'research', url: 'https://catalog.registrar.ucla.edu/About-UCLA/Research-Programs' },
      { kind: 'doctoral', url: 'https://grad.ucla.edu/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of California, San Diego',
    region: 'US',
    allowedHosts: [
      'artsandhumanities.ucsd.edu',
      'biology.ucsd.edu',
      'jacobs.ucsd.edu',
      'catalog.ucsd.edu',
    ],
    seeds: [
      { kind: 'departments', url: 'https://biology.ucsd.edu/research/academic-departments/index.html' },
      {
        kind: 'faculty',
        url: 'https://artsandhumanities.ucsd.edu/faculty-research/faculty-directory/index.html',
      },
      { kind: 'research', url: 'https://jacobs.ucsd.edu/research/centers-institutes' },
      { kind: 'doctoral', url: 'https://catalog.ucsd.edu/graduate/degrees-offered/index.html' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Michigan',
    region: 'US',
    allowedHosts: ['umich.edu', 'cse.engin.umich.edu', 'research.umich.edu', 'rackham.umich.edu'],
    seeds: [
      {
        kind: 'departments',
        url: 'https://umich.edu/schools-colleges/',
      },
      {
        kind: 'faculty',
        url: 'https://cse.engin.umich.edu/people/faculty/',
      },
      {
        kind: 'research',
        url: 'https://research.umich.edu/research-initiatives/u-m-research-centers-institutes/',
      },
      {
        kind: 'doctoral',
        url: 'https://rackham.umich.edu/programs-of-study/',
      },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'The University of Texas at Austin',
    region: 'US',
    allowedHosts: ['ece.utexas.edu', 'www.utexas.edu', 'research.utexas.edu', 'gradschool.utexas.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.utexas.edu/academics/areas-of-study' },
      { kind: 'faculty', url: 'https://ece.utexas.edu/people/faculty' },
      { kind: 'research', url: 'https://research.utexas.edu/research-centers-units' },
      { kind: 'doctoral', url: 'https://gradschool.utexas.edu/degrees-programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
]
