const US_PATH_HINTS = Object.freeze({
  faculty: Object.freeze([
    'faculty',
    'people',
    'directory',
    'profile',
    'profiles',
    'expert',
    'experts',
    'researcher',
    'professor',
    'advisor',
  ]),
  lab: Object.freeze([
    'research',
    'lab',
    'labs',
    'laboratory',
    'laboratories',
    'group',
    'groups',
    'center',
    'centers',
    'centre',
    'centres',
    'institute',
    'institutes',
    'facility',
    'facilities',
  ]),
  department: Object.freeze([
    'department',
    'departments',
    'school',
    'schools',
    'college',
    'colleges',
    'academic-unit',
    'academics',
    'discipline',
    'disciplines',
  ]),
  program: Object.freeze([
    'phd',
    'ph-d',
    'doctoral',
    'doctorate',
    'graduate',
    'postgraduate',
    'program',
    'programs',
    'degree',
    'degrees',
    'admission',
    'admissions',
  ]),
})

export const SCHOOL_ADAPTERS_BATCH_03 = [
  {
    school: 'University of Minnesota',
    region: 'US',
    allowedHosts: ['olpd.umn.edu', 'cse.umn.edu', 'research.umn.edu', 'grad.umn.edu'],
    seeds: [
      { kind: 'departments', url: 'https://cse.umn.edu/college/departments-and-majors/departments' },
      { kind: 'faculty', url: 'https://olpd.umn.edu/faculty' },
      { kind: 'research', url: 'https://research.umn.edu/resources/expertise-facilities' },
      { kind: 'doctoral', url: 'https://grad.umn.edu/graduate-programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'The Ohio State University',
    region: 'US',
    allowedHosts: ['cph.osu.edu', 'artsandsciences.osu.edu', 'research.osu.edu', 'gradsch.osu.edu'],
    seeds: [
      { kind: 'departments', url: 'https://artsandsciences.osu.edu/academics/departments-centers' },
      { kind: 'faculty', url: 'https://cph.osu.edu/people' },
      { kind: 'research', url: 'https://research.osu.edu/about-us/multidisciplinary-research-centers-and-areas' },
      { kind: 'doctoral', url: 'https://gradsch.osu.edu/future-students/find-your-program' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'The Pennsylvania State University',
    region: 'US',
    allowedHosts: ['www.ems.psu.edu', 'la.psu.edu', 'research.psu.edu', 'bulletins.psu.edu'],
    seeds: [
      { kind: 'departments', url: 'https://la.psu.edu/schools-departments-and-programs/' },
      { kind: 'faculty', url: 'https://www.ems.psu.edu/research-faculty/about-our-faculty/find-faculty-member' },
      { kind: 'research', url: 'https://research.psu.edu/' },
      { kind: 'doctoral', url: 'https://bulletins.psu.edu/graduate-professional-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Virginia Tech',
    region: 'US',
    allowedHosts: ['website.cs.vt.edu', 'eng.vt.edu', 'www.research.vt.edu'],
    seeds: [
      { kind: 'departments', url: 'https://eng.vt.edu/about/departments.html' },
      { kind: 'faculty', url: 'https://website.cs.vt.edu/people/faculty.html' },
      { kind: 'research', url: 'https://www.research.vt.edu/about/institutes.html' },
      { kind: 'doctoral', url: 'https://eng.vt.edu/graduate/graduate-programs.html' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Northeastern University',
    region: 'US',
    allowedHosts: ['cos.northeastern.edu', 'www.northeastern.edu', 'research.northeastern.edu', 'catalog.northeastern.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.northeastern.edu/academics/colleges-and-schools/' },
      { kind: 'faculty', url: 'https://cos.northeastern.edu/people/' },
      { kind: 'research', url: 'https://research.northeastern.edu/institutes-and-centers/' },
      { kind: 'doctoral', url: 'https://catalog.northeastern.edu/graduate/phdprograms/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Rice University',
    region: 'US',
    allowedHosts: ['sci.rice.edu', 'ga.rice.edu', 'research.rice.edu'],
    seeds: [
      { kind: 'departments', url: 'https://ga.rice.edu/programs-study/departments-programs/' },
      { kind: 'faculty', url: 'https://sci.rice.edu/directory' },
      { kind: 'research', url: 'https://research.rice.edu/research-institutes-and-centers' },
      { kind: 'doctoral', url: 'https://ga.rice.edu/graduate-students/academic-opportunities/degrees/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Brown University',
    region: 'US',
    allowedHosts: ['education.brown.edu', 'www.brown.edu', 'graduateprograms.brown.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.brown.edu/academics/departments' },
      { kind: 'faculty', url: 'https://education.brown.edu/faculty/faculty-directory' },
      { kind: 'research', url: 'https://www.brown.edu/academics/centers-institutes' },
      { kind: 'doctoral', url: 'https://graduateprograms.brown.edu/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Dartmouth College',
    region: 'US',
    allowedHosts: ['faculty-directory.dartmouth.edu', 'home.dartmouth.edu', 'graduate.dartmouth.edu'],
    seeds: [
      { kind: 'departments', url: 'https://home.dartmouth.edu/academics/departments-programs' },
      { kind: 'faculty', url: 'https://faculty-directory.dartmouth.edu/' },
      { kind: 'research', url: 'https://graduate.dartmouth.edu/mcb/centers-and-programs/research-resources-centers' },
      { kind: 'doctoral', url: 'https://graduate.dartmouth.edu/admissions/programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'The University of Chicago',
    region: 'US',
    allowedHosts: ['socialsciences.uchicago.edu', 'provost.uchicago.edu', 'grad.uchicago.edu'],
    seeds: [
      { kind: 'departments', url: 'https://socialsciences.uchicago.edu/faculty/departments' },
      { kind: 'faculty', url: 'https://socialsciences.uchicago.edu/faculty' },
      { kind: 'research', url: 'https://provost.uchicago.edu/issues/centers-and-institutes' },
      { kind: 'doctoral', url: 'https://grad.uchicago.edu/admissions/programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Pittsburgh',
    region: 'US',
    allowedHosts: ['www.as.pitt.edu', 'www.sci.pitt.edu', 'www.research.pitt.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.sci.pitt.edu/about/departments-programs-and-institutes' },
      { kind: 'faculty', url: 'https://www.as.pitt.edu/faculty/directory' },
      { kind: 'research', url: 'https://www.research.pitt.edu/centers-and-institutes' },
      { kind: 'doctoral', url: 'https://www.sci.pitt.edu/academics/doctoral-degrees' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Rutgers University',
    region: 'US',
    allowedHosts: ['www.cs.rutgers.edu', 'sas.rutgers.edu', 'academicaffairs.rutgers.edu', 'rge.sas.rutgers.edu'],
    seeds: [
      { kind: 'departments', url: 'https://sas.rutgers.edu/academics/departments-programs-and-centers' },
      { kind: 'faculty', url: 'https://www.cs.rutgers.edu/people/directory.php?type=faculty' },
      { kind: 'research', url: 'https://academicaffairs.rutgers.edu/explore-rutgers-research-centers-and-institutes' },
      { kind: 'doctoral', url: 'https://rge.sas.rutgers.edu/graduate-education/phd-programs' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Stony Brook University',
    region: 'US',
    allowedHosts: ['www.stonybrook.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.stonybrook.edu/commcms/cas/departments' },
      { kind: 'faculty', url: 'https://www.stonybrook.edu/neurobiology/people/faculty-directory.html' },
      { kind: 'research', url: 'https://www.stonybrook.edu/about/centers-and-institutes/' },
      { kind: 'doctoral', url: 'https://www.stonybrook.edu/grad/academics/programs.php' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Arizona State University',
    region: 'US',
    allowedHosts: ['search.asu.edu', 'www.asu.edu', 'engineering.asu.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.asu.edu/academics/colleges-schools' },
      { kind: 'faculty', url: 'https://search.asu.edu/view/directory-profiles' },
      { kind: 'research', url: 'https://www.asu.edu/academics/centers-and-institutes' },
      { kind: 'doctoral', url: 'https://engineering.asu.edu/degrees/graduate/all/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'Texas A&M University',
    region: 'US',
    allowedHosts: ['artsci.tamu.edu', 'research.tamu.edu', 'catalog.tamu.edu'],
    seeds: [
      { kind: 'departments', url: 'https://artsci.tamu.edu/academics/departments-programs.html' },
      { kind: 'faculty', url: 'https://artsci.tamu.edu/biology/contact/faculty.html' },
      { kind: 'research', url: 'https://research.tamu.edu/research-support/centers-and-institutes/' },
      { kind: 'doctoral', url: 'https://catalog.tamu.edu/graduate/degrees-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of North Carolina at Chapel Hill',
    region: 'US',
    allowedHosts: ['cs.unc.edu', 'catalog.unc.edu', 'research.unc.edu', 'gradschool.unc.edu'],
    seeds: [
      { kind: 'departments', url: 'https://catalog.unc.edu/undergraduate/departments/' },
      { kind: 'faculty', url: 'https://cs.unc.edu/about/people/' },
      { kind: 'research', url: 'https://research.unc.edu/' },
      { kind: 'doctoral', url: 'https://gradschool.unc.edu/degree-programs/' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
  {
    school: 'University of Colorado Boulder',
    region: 'US',
    allowedHosts: ['experts.colorado.edu', 'www.colorado.edu'],
    seeds: [
      { kind: 'departments', url: 'https://www.colorado.edu/asfacultystaff/departmental-listing' },
      { kind: 'faculty', url: 'https://experts.colorado.edu/display/deptid_10344' },
      { kind: 'research', url: 'https://www.colorado.edu/researchinnovation/research-institutes-cu-boulder' },
      { kind: 'doctoral', url: 'https://www.colorado.edu/graduateschool/admissions/where-begin/program-information-deadlines' },
    ],
    pathHints: US_PATH_HINTS,
    verifiedAt: '2026-07-22',
  },
]
