/**
 * Full preset icon catalog (100+). Single source for ids, Lucide components, and
 * en/zh labels used when i18n packs are incomplete.
 */
import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlignLeft,
  Archive,
  Atom,
  Award,
  BadgeCheck,
  Banknote,
  BarChart3,
  Beaker,
  Bell,
  Bookmark,
  BookMarked,
  BookOpen,
  Bot,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  ChartNoAxesCombined,
  CheckSquare,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudUpload,
  Code2,
  Coins,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Database,
  Dna,
  Earth,
  ExternalLink,
  Eye,
  File,
  FileArchive,
  FileAudio,
  FileCheck2,
  FileCode2,
  FileImage,
  FileJson,
  FileKey,
  FilePen,
  FileSearch,
  FileSpreadsheet,
  FileStack,
  FileText,
  FileVideo,
  Film,
  Filter,
  Flag,
  FlaskConical,
  Folder,
  FolderGit2,
  FolderKanban,
  FolderOpen,
  FolderTree,
  Gift,
  GitBranch,
  GitMerge,
  Globe,
  GraduationCap,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Highlighter,
  History,
  Home,
  Hourglass,
  IdCard,
  Image,
  Inbox,
  Kanban,
  Key,
  Languages,
  Laptop,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  LineChart,
  Link2,
  ListChecks,
  ListTodo,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageSquare,
  Mic,
  Microscope,
  Monitor,
  Moon,
  Music,
  Network,
  Newspaper,
  NotebookPen,
  Package,
  Palette,
  Paperclip,
  PenLine,
  Pencil,
  Percent,
  Phone,
  PieChart,
  Pin,
  Plane,
  Presentation,
  Quote,
  Receipt,
  Rocket,
  Ruler,
  Scale,
  School,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sigma,
  Sparkles,
  Sprout,
  Star,
  StickyNote,
  Sun,
  Target,
  Terminal,
  TestTube,
  Timer,
  TrendingUp,
  Trophy,
  University,
  User,
  UserCheck,
  Users,
  Video,
  Wallet,
  Wand2,
  Workflow,
  Wrench,
} from 'lucide-react'

export const PROFILE_PRESET_ICON_CATALOG = [
  // Existing defaults first (stable for older presets)
  { id: 'file-text', Icon: FileText, en: 'Document', zh: '文档' },
  { id: 'file-check', Icon: FileCheck2, en: 'Approved document', zh: '已确认文档' },
  { id: 'briefcase', Icon: BriefcaseBusiness, en: 'Portfolio', zh: '作品集' },
  { id: 'graduation-cap', Icon: GraduationCap, en: 'Academic record', zh: '学术记录' },
  { id: 'flask-conical', Icon: FlaskConical, en: 'Research', zh: '研究' },
  { id: 'scroll-text', Icon: ScrollText, en: 'Statement', zh: '陈述' },
  { id: 'mail', Icon: Mail, en: 'Letter', zh: '信件' },
  { id: 'pen-line', Icon: PenLine, en: 'Writing', zh: '写作' },
  { id: 'book-open', Icon: BookOpen, en: 'Reading', zh: '阅读资料' },

  // Files & folders
  { id: 'file', Icon: File, en: 'File', zh: '文件' },
  { id: 'file-stack', Icon: FileStack, en: 'File stack', zh: '文件叠' },
  { id: 'file-search', Icon: FileSearch, en: 'Find file', zh: '查找文件' },
  { id: 'file-spreadsheet', Icon: FileSpreadsheet, en: 'Spreadsheet', zh: '表格文件' },
  { id: 'file-code', Icon: FileCode2, en: 'Code file', zh: '代码文件' },
  { id: 'file-json', Icon: FileJson, en: 'JSON file', zh: 'JSON 文件' },
  { id: 'file-image', Icon: FileImage, en: 'Image file', zh: '图片文件' },
  { id: 'file-video', Icon: FileVideo, en: 'Video file', zh: '视频文件' },
  { id: 'file-audio', Icon: FileAudio, en: 'Audio file', zh: '音频文件' },
  { id: 'file-archive', Icon: FileArchive, en: 'Archive file', zh: '压缩包' },
  { id: 'file-pen', Icon: FilePen, en: 'Edit file', zh: '编辑文件' },
  { id: 'file-key', Icon: FileKey, en: 'Secure file', zh: '加密文件' },
  { id: 'folder', Icon: Folder, en: 'Folder', zh: '文件夹' },
  { id: 'folder-open', Icon: FolderOpen, en: 'Open folder', zh: '打开文件夹' },
  { id: 'folder-tree', Icon: FolderTree, en: 'Folder tree', zh: '文件夹树' },
  { id: 'folder-kanban', Icon: FolderKanban, en: 'Project folder', zh: '项目文件夹' },
  { id: 'folder-git', Icon: FolderGit2, en: 'Git folder', zh: '代码仓库夹' },
  { id: 'archive', Icon: Archive, en: 'Archive', zh: '归档' },
  { id: 'clipboard-list', Icon: ClipboardList, en: 'Clipboard list', zh: '清单剪贴板' },
  { id: 'clipboard-check', Icon: ClipboardCheck, en: 'Clipboard check', zh: '已核对清单' },
  { id: 'sticky-note', Icon: StickyNote, en: 'Sticky note', zh: '便签' },
  { id: 'notebook-pen', Icon: NotebookPen, en: 'Notebook', zh: '笔记本' },
  { id: 'newspaper', Icon: Newspaper, en: 'Newspaper', zh: '报刊' },
  { id: 'library', Icon: Library, en: 'Library', zh: '图书馆' },
  { id: 'book-marked', Icon: BookMarked, en: 'Bookmarked', zh: '书签书' },

  // Academia & research
  { id: 'school', Icon: School, en: 'School', zh: '学校' },
  { id: 'university', Icon: University, en: 'University', zh: '大学' },
  { id: 'atom', Icon: Atom, en: 'Atom', zh: '原子' },
  { id: 'microscope', Icon: Microscope, en: 'Microscope', zh: '显微镜' },
  { id: 'dna', Icon: Dna, en: 'DNA', zh: '基因' },
  { id: 'brain', Icon: Brain, en: 'Brain', zh: '大脑' },
  { id: 'brain-circuit', Icon: BrainCircuit, en: 'AI brain', zh: '智能脑' },
  { id: 'beaker', Icon: Beaker, en: 'Beaker', zh: '烧杯' },
  { id: 'test-tube', Icon: TestTube, en: 'Test tube', zh: '试管' },
  { id: 'lightbulb', Icon: Lightbulb, en: 'Idea', zh: '灵感' },
  { id: 'presentation', Icon: Presentation, en: 'Presentation', zh: '演示' },
  { id: 'calculator', Icon: Calculator, en: 'Calculator', zh: '计算器' },
  { id: 'ruler', Icon: Ruler, en: 'Ruler', zh: '尺规' },
  { id: 'sigma', Icon: Sigma, en: 'Sigma', zh: '求和' },

  // Writing & communication
  { id: 'pencil', Icon: Pencil, en: 'Pencil', zh: '铅笔' },
  { id: 'highlighter', Icon: Highlighter, en: 'Highlighter', zh: '荧光笔' },
  { id: 'quote', Icon: Quote, en: 'Quote', zh: '引用' },
  { id: 'align-left', Icon: AlignLeft, en: 'Text block', zh: '文本块' },
  { id: 'message-square', Icon: MessageSquare, en: 'Message', zh: '消息' },
  { id: 'send', Icon: Send, en: 'Send', zh: '发送' },
  { id: 'inbox', Icon: Inbox, en: 'Inbox', zh: '收件箱' },
  { id: 'phone', Icon: Phone, en: 'Phone', zh: '电话' },
  { id: 'video', Icon: Video, en: 'Video call', zh: '视频通话' },
  { id: 'megaphone', Icon: Megaphone, en: 'Announcement', zh: '公告' },
  { id: 'bell', Icon: Bell, en: 'Notification', zh: '通知' },
  { id: 'languages', Icon: Languages, en: 'Languages', zh: '语言' },
  { id: 'mic', Icon: Mic, en: 'Microphone', zh: '麦克风' },
  { id: 'headphones', Icon: Headphones, en: 'Headphones', zh: '耳机' },

  // People & identity
  { id: 'user', Icon: User, en: 'Person', zh: '个人' },
  { id: 'users', Icon: Users, en: 'People', zh: '团队' },
  { id: 'user-check', Icon: UserCheck, en: 'Verified person', zh: '已验证人员' },
  { id: 'contact', Icon: Contact, en: 'Contact', zh: '联系人' },
  { id: 'id-card', Icon: IdCard, en: 'ID card', zh: '证件' },
  { id: 'badge-check', Icon: BadgeCheck, en: 'Verified badge', zh: '认证徽章' },
  { id: 'handshake', Icon: Handshake, en: 'Handshake', zh: '合作' },

  // Achievement & goals
  { id: 'award', Icon: Award, en: 'Award', zh: '奖项' },
  { id: 'medal', Icon: Medal, en: 'Medal', zh: '奖牌' },
  { id: 'trophy', Icon: Trophy, en: 'Trophy', zh: '奖杯' },
  { id: 'star', Icon: Star, en: 'Star', zh: '星标' },
  { id: 'sparkles', Icon: Sparkles, en: 'Sparkles', zh: '高亮' },
  { id: 'target', Icon: Target, en: 'Target', zh: '目标' },
  { id: 'flag', Icon: Flag, en: 'Flag', zh: '旗帜' },
  { id: 'rocket', Icon: Rocket, en: 'Rocket', zh: '火箭' },
  { id: 'plane', Icon: Plane, en: 'Travel', zh: '出行' },

  // Places
  { id: 'home', Icon: Home, en: 'Home', zh: '主页' },
  { id: 'building', Icon: Building2, en: 'Building', zh: '建筑' },
  { id: 'globe', Icon: Globe, en: 'Globe', zh: '全球' },
  { id: 'earth', Icon: Earth, en: 'Earth', zh: '地球' },
  { id: 'map', Icon: Map, en: 'Map', zh: '地图' },
  { id: 'map-pin', Icon: MapPin, en: 'Location', zh: '地点' },
  { id: 'compass', Icon: Compass, en: 'Compass', zh: '指南针' },

  // Time & tasks
  { id: 'calendar', Icon: Calendar, en: 'Calendar', zh: '日历' },
  { id: 'calendar-check', Icon: CalendarCheck, en: 'Scheduled', zh: '已安排' },
  { id: 'calendar-clock', Icon: CalendarClock, en: 'Deadline', zh: '截止时间' },
  { id: 'clock', Icon: Clock, en: 'Clock', zh: '时钟' },
  { id: 'timer', Icon: Timer, en: 'Timer', zh: '计时器' },
  { id: 'hourglass', Icon: Hourglass, en: 'Hourglass', zh: '沙漏' },
  { id: 'history', Icon: History, en: 'History', zh: '历史' },
  { id: 'list-checks', Icon: ListChecks, en: 'Checklist', zh: '检查清单' },
  { id: 'list-todo', Icon: ListTodo, en: 'To-do', zh: '待办' },
  { id: 'check-square', Icon: CheckSquare, en: 'Done', zh: '完成' },
  { id: 'kanban', Icon: Kanban, en: 'Kanban', zh: '看板' },
  { id: 'workflow', Icon: Workflow, en: 'Workflow', zh: '工作流' },
  { id: 'filter', Icon: Filter, en: 'Filter', zh: '筛选' },
  { id: 'search', Icon: Search, en: 'Search', zh: '搜索' },

  // Data & tech
  { id: 'bar-chart', Icon: BarChart3, en: 'Bar chart', zh: '柱状图' },
  { id: 'line-chart', Icon: LineChart, en: 'Line chart', zh: '折线图' },
  { id: 'pie-chart', Icon: PieChart, en: 'Pie chart', zh: '饼图' },
  { id: 'trending-up', Icon: TrendingUp, en: 'Trend up', zh: '上升趋势' },
  { id: 'activity', Icon: Activity, en: 'Activity', zh: '活跃度' },
  { id: 'chart', Icon: ChartNoAxesCombined, en: 'Chart', zh: '图表' },
  { id: 'database', Icon: Database, en: 'Database', zh: '数据库' },
  { id: 'server', Icon: Server, en: 'Server', zh: '服务器' },
  { id: 'cpu', Icon: Cpu, en: 'CPU', zh: '处理器' },
  { id: 'hard-drive', Icon: HardDrive, en: 'Storage', zh: '存储' },
  { id: 'laptop', Icon: Laptop, en: 'Laptop', zh: '笔记本电脑' },
  { id: 'monitor', Icon: Monitor, en: 'Monitor', zh: '显示器' },
  { id: 'code', Icon: Code2, en: 'Code', zh: '代码' },
  { id: 'terminal', Icon: Terminal, en: 'Terminal', zh: '终端' },
  { id: 'git-branch', Icon: GitBranch, en: 'Git branch', zh: '分支' },
  { id: 'git-merge', Icon: GitMerge, en: 'Git merge', zh: '合并' },
  { id: 'bot', Icon: Bot, en: 'Bot', zh: '机器人' },
  { id: 'wand', Icon: Wand2, en: 'Magic wand', zh: '魔法棒' },
  { id: 'network', Icon: Network, en: 'Network', zh: '网络' },
  { id: 'cloud', Icon: Cloud, en: 'Cloud', zh: '云' },
  { id: 'cloud-upload', Icon: CloudUpload, en: 'Upload', zh: '上传' },
  { id: 'cloud-download', Icon: CloudDownload, en: 'Download', zh: '下载' },
  { id: 'link', Icon: Link2, en: 'Link', zh: '链接' },
  { id: 'external-link', Icon: ExternalLink, en: 'External link', zh: '外链' },
  { id: 'paperclip', Icon: Paperclip, en: 'Attachment', zh: '附件' },
  { id: 'pin', Icon: Pin, en: 'Pin', zh: '固定' },
  { id: 'bookmark', Icon: Bookmark, en: 'Bookmark', zh: '书签' },

  // Design & media
  { id: 'image', Icon: Image, en: 'Image', zh: '图片' },
  { id: 'camera', Icon: Camera, en: 'Camera', zh: '相机' },
  { id: 'film', Icon: Film, en: 'Film', zh: '影片' },
  { id: 'music', Icon: Music, en: 'Music', zh: '音乐' },
  { id: 'palette', Icon: Palette, en: 'Palette', zh: '调色板' },
  { id: 'layers', Icon: Layers, en: 'Layers', zh: '图层' },
  { id: 'layout-grid', Icon: LayoutGrid, en: 'Grid', zh: '网格' },
  { id: 'eye', Icon: Eye, en: 'Preview', zh: '预览' },

  // Finance & legal
  { id: 'wallet', Icon: Wallet, en: 'Wallet', zh: '钱包' },
  { id: 'coins', Icon: Coins, en: 'Coins', zh: '硬币' },
  { id: 'credit-card', Icon: CreditCard, en: 'Card', zh: '银行卡' },
  { id: 'receipt', Icon: Receipt, en: 'Receipt', zh: '收据' },
  { id: 'banknote', Icon: Banknote, en: 'Banknote', zh: '钞票' },
  { id: 'circle-dollar', Icon: CircleDollarSign, en: 'Dollar', zh: '金额' },
  { id: 'percent', Icon: Percent, en: 'Percent', zh: '百分比' },
  { id: 'scale', Icon: Scale, en: 'Balance scale', zh: '天平' },
  { id: 'shield', Icon: Shield, en: 'Shield', zh: '盾牌' },
  { id: 'shield-check', Icon: ShieldCheck, en: 'Security check', zh: '安全校验' },
  { id: 'lock', Icon: Lock, en: 'Lock', zh: '锁定' },
  { id: 'key', Icon: Key, en: 'Key', zh: '密钥' },

  // Nature & misc
  { id: 'heart', Icon: Heart, en: 'Heart', zh: '心形' },
  { id: 'heart-pulse', Icon: HeartPulse, en: 'Health', zh: '健康' },
  { id: 'leaf', Icon: Leaf, en: 'Leaf', zh: '叶子' },
  { id: 'sprout', Icon: Sprout, en: 'Sprout', zh: '萌芽' },
  { id: 'sun', Icon: Sun, en: 'Sun', zh: '太阳' },
  { id: 'moon', Icon: Moon, en: 'Moon', zh: '月亮' },
  { id: 'gift', Icon: Gift, en: 'Gift', zh: '礼物' },
  { id: 'package', Icon: Package, en: 'Package', zh: '包裹' },
  { id: 'settings', Icon: Settings, en: 'Settings', zh: '设置' },
  { id: 'wrench', Icon: Wrench, en: 'Tools', zh: '工具' },
  { id: 'share', Icon: Share2, en: 'Share', zh: '分享' },
  { id: 'briefcase-alt', Icon: Briefcase, en: 'Briefcase', zh: '公文包' },
] as const

export type ProfilePresetIconName = (typeof PROFILE_PRESET_ICON_CATALOG)[number]['id']

/** Stable list of icon ids for pickers and validation. */
export const PROFILE_PRESET_ICONS: readonly ProfilePresetIconName[] = PROFILE_PRESET_ICON_CATALOG.map(
  (entry) => entry.id,
)

export const profilePresetIconComponents = Object.fromEntries(
  PROFILE_PRESET_ICON_CATALOG.map((entry) => [entry.id, entry.Icon]),
) as Record<ProfilePresetIconName, LucideIcon>

export const profilePresetIconLabelMap = Object.fromEntries(
  PROFILE_PRESET_ICON_CATALOG.map((entry) => [entry.id, { en: entry.en, zh: entry.zh }]),
) as Record<ProfilePresetIconName, { en: string; zh: string }>

export function profilePresetIconSearchText(id: string, localizedLabel = ''): string {
  const labels = profilePresetIconLabelMap[id as ProfilePresetIconName]
  return [id, localizedLabel, labels?.en, labels?.zh].filter(Boolean).join(' ').toLowerCase()
}
